title: My Portfolio
description: UX Design & Case Studies
theme: minima
markdown: kramdown

url: "https://www.bamoore.com"
baseurl: ""

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  case-studies:
    output: true
    permalink: /case-studies/:name
