#-------------------------------
# Site Settings
title: BAMoore
logo: # You can add own logo. For example '/images/logo.png'.
description: Personal UX design portfolio.
color_scheme: auto # auto, light, or dark

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Work'
      url: '/work/'
    - title: 'About'
      url: '/about/'
    # - title: 'Writing'
    #   url: '/blog/'
    - title: 'Contact'
      url: '/contact/'

#-------------------------------
# Author Settings
author:
  author__name: Brenden
  author__bio: Designing digital experiences from the City of Brotherly Love.
  author__avatar: '/images/01.jpg'

social:
  - icon: ion-logo-twitter
    link: https://twitter.com
  - icon: ion-logo-facebook
    link: https://facebook.com
  - icon: ion-logo-instagram
    link: https://instagram.com
  - icon: ion-logo-github
    link: https://github.com
  - icon: ion-logo-vimeo
    link: https://vimeo.com

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero__title: Hey everyone, I’m Brenden
  hero__description: Hi, I'm Brenden – UX designer focused on clear flows, measurable outcomes, and ship-ready specs. But don't just take my word for it, <a href="#testimonials" class="hero-testimonial-link">see what others are saying <i class="ion ion-md-arrow-forward"></i></a>
  hero__image: "/images/01-1.jpg"

#-------------------------------
# Logos Settings
logos:
  enable: true
  logos__title: I’ve worked with some great companies

logo__items:
  - name: Google
    link: "https://www.google.com/"
    image: "/images/google.svg"
  - name: Spotify
    link: "https://www.spotify.com/"
    image: "/images/spotify.svg"
  - name: Netlify
    link: "https://www.netlify.com/"
    image: "/images/netlify.svg"
  - name: Apple
    link: "https://www.apple.com/"
    image: "/images/apple.svg"
  - name: Adobe
    link: "https://www.adobe.com/"
    image: "/images/adobe.svg"

#-------------------------------
# Newsletter
# mailchimp:
#   enable: false
#   mailchimp__identifier: ""
#   mailchimp__input__text: Your email address...
#   mailchimp__button__text: Subscribe

#-------------------------------
# Work Settings
work:
  enable: true
  work__title: Work
  work__description: I shows only the best websites and portfolios built completely with passion, simplicity & creativity!

#-------------------------------
# Testimonials Section
testimonials:
  enable: true

testimonial__title: Testimonials
testimonial__description:

testimonial__items:
  - name: "E.Jerome"
    image: "/images/client-1.jpg"
    designation: "Lead Frontend Developer"
    link: ""
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
  - name: "Carla Rosser"
    image: "/images/client-2.jpg"
    designation: "Statistician"
    link: "https://facebook.com/"
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
  - name: "Maria Curtis"
    image: "/images/client-3.jpg"
    designation: "Team Lead"
    link: "https://twitter.com/"
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
  - name: "Carter Bergson"
    image: "/images/client-4.jpg"
    designation: "CEO, Founder"
    link: "https://facebook.com/"
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
  - name: "Jordyn Franci"
    image: "/images/client-5.jpg"
    designation: "Personal Trainer"
    link: "https://twitter.com/"
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
  - name: "Mira Carder"
    image: "/images/client-6.jpg"
    designation: "Data Scientist"
    link: "https://facebook.com/"
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
  - name: "Madelyn Herwitz"
    image: "/images/client-7.jpg"
    designation: "Frontend Engineer"
    link: "https://twitter.com/"
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
  - name: "Anika Schleifer"
    image: "/images/client-8.jpg"
    designation: "Fitness Director"
    link: "https://facebook.com/"
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"
  - name: "Wilson Dorwart"
    image: "/images/client-9.jpg"
    designation: "Financial Manager"
    link: "https://twitter.com/"
    content: "Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration"

#-------------------------------
# Blog Section
# blog:
#   enable: true
# blog__settings:
#   blog__title: Writing
#   blog__description:

#-------------------------------
# Footer Settings
footer__background__image: "/images/footer-bg.jpg"

#-------------------------------
# Contact Settings
contact:
  email: bamoore@proton.me
  description: Ready to discuss your next project? Drop me a message and I'll get back to you within 24 hours. Let's create something amazing together.

#-------------------------------
# Comment Section (Disqus)
# disqus:
#   enable: false
#   disqus__identifier: anvod-studio-test

#-------------------------------
# Google Analytics
google-analytics: G-QGVZS40STR
